Assignment= "Numpy"

In [7]:
#ques1-" Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.""

import numpy as np

arr =np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
# ques2-" Given a NumPy array 'arr', check if its data type is float64."

arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print(" The given data is float64")

else:
    print(" The Given data is not float64")

 The given data is float64


In [9]:
# ques3-"Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers."

arr=np.array([1+2j,3+4j,5+9j])

arr
arr.dtype

dtype('complex128')

In [10]:
# ques4-"Convert an existing NumPy array 'arr' of integers to float32 data type."

arr=np.array([1,2,3,4,5,6])

arr=arr.astype("float32")

arr

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [11]:
# ques5-"Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision."

arr=np.array([1.1,2.2,3.3,4.4,5.5])

arr.dtype
arr.astype(np.float32)

array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float32)

In [12]:
# ques6-"Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
#  type"


array_attributes=(np.array([[1, 2, 3], [4, 5, 6]]))

[array_attributes.shape], [array_attributes.size], [array_attributes.dtype]


([(2, 3)], [6], [dtype('int64')])

In [13]:
# ques7-"Create a function array_dimension that takes a NumPy array as input and returns its dimensionality"

import numpy as np

array_dimension= (np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]))

array_dimension.ndim

3

In [14]:
# ques8-"Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
# size in bytes"

item_size_info= (np.array([[1,2,3],[4,5,6]]))

item_size_info.itemsize, item_size_info.nbytes

(8, 48)

In [15]:
# ques9-" Create a function array_strides that takes a NumPy array as input and returns the strides of the array."

array_strides=(np.array([[1,2,3],[4,5,6]]))

print(array_strides.strides)

(24, 8)


In [16]:
# ques10-"Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array."

shape_stride_relationship= (np.array([[1,2,3],[4,5,6]]))

(shape_stride_relationship.shape),(shape_stride_relationship.strides)

((2, 3), (24, 8))

In [17]:
# ques11-"Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements"
n=5
create_zeros_array = (np.zeros(n).astype(int))
print(create_zeros_array)



[0 0 0 0 0]


In [18]:
# ques12-" Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`."
 

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 3
cols = 4
result = (create_ones_matrix(rows, cols).astype(int))
print(result)

# result.dtype


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
# ques13-" Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step"

start=int(input("enter the start value:"))
stop=int(input("enter the stop value:"))
step=int(input("enter the step value:"))

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)


generate_range_array(start,stop,step)
    

ValueError: invalid literal for int() with base 10: ''

In [34]:
# ques14-"Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive)"


start=0.0
stop=1.0
num=5

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

generate_linear_space(start,stop,num)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#ques15- "Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye".

import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
#  ques16-"Write a function that takes a Python list and converts it into a NumPy array."

import numpy as np

def list_to_array(lst):
    return np.array(lst)

lst = [1, 2, 3, 4, 5]
arr = list_to_array(lst)
print(arr)


[1 2 3 4 5]


In [4]:
# ques17-"Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data."

import numpy as np  

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr.view()
print("Original array:", arr)
print("New array:", new_arr)




Original array: [1 2 3 4 5]
New array: [1 2 3 4 5]


In [7]:
#  ques18-"Write a function that takes two NumPy arrays and concatenates them along a specified axis."

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = concatenate_arrays(arr1, arr2, axis=0)
print(result)

[1 2 3 4 5 6]


In [8]:
# ques19-"Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
# concatenate`."



arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6, 7])

concatenated_arr = np.concatenate((arr1, arr2))

print(concatenated_arr)

[1 2 3 4 5 6 7]


In [9]:
# ques20- "Write a function that vertically stacks multiple NumPy arrays given as a list."

array_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

np.vstack(array_list)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# ques21-"Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size."

def array_of_integers(start, end, step):
    return np.arange(start, end+1, step)

print(array_of_integers(1, 10, 2))



[1 3 5 7 9]


In [ ]:
# ques22-"Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# (inclusive)."

def eq_spaced_array(start,end,num):
    import numpy as np
    return np. linspace(start,end,num)

eq_spaced_array(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
# ques23-"Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive)."

import numpy as np

def log_spaced_array(start, end, num):
    return np.logspace(start, end, num, base=10)

start = 1
end = 3
num = 5 

log_spaced_array(start, end, num)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

In [ ]:
import numpy as np
import panda as pd

In [ ]:
# ques24-" Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100."

import pandas as pd
import numpy as np

arr = np.random.randint(1, 69, size=(5, 3))

df = pd.DataFrame(arr)

print(df)

    0   1   2
0  32  31  44
1  54  51  10
2  63   8  24
3  40  50  19
4  62  42  64


In [23]:
# ques25-"Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame."

df=pd.DataFrame({'A':[1,2,3,4,-5],'B':[10,20,30,40,-50],'C':[100,200,300,400,500]})

df[df<0]=0

df




A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  0   0  500

In [26]:
# ques26-"Access the 3rd element from the given NumPy array"

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])



30


In [27]:
# ques27-"Retrieve the element at index (1, 2) from the 2D NumPy array."

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]
print("Element at index (1, 2):", element)


Element at index (1, 2): 6


In [39]:
# ques28-". Using boolean indexing, extract elements greater than 5 from the given NumPy array."

arr = np.array([3, 8, 2, 10, 5, 7])

result=arr[arr>5]

print(f"element greater than 5 are:{result}")

print(arr>5)

element greater than 5 are:[ 8 10  7]
[False  True False  True False  True]


In [40]:
# ques29-"Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array".

my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sliced_array = my_array[2:6]

print("Original Array:", my_array)
print("Sliced Array:", sliced_array)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliced Array: [3 4 5 6]


In [41]:
# ques30-" Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array."

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


sub_array = arr_2d[1:3, 1:3]

print(sub_array)


[[5 6]
 [8 9]]


In [44]:
# ques31-"Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array."

arr_dd=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_dd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# ques32-"Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing."

arr=np.array([1,2,3,4,5,6,7,8,9,10])

threshold=5

print(arr[arr>threshold])

[ 6  7  8  9 10]


In [46]:
# ques33-"Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension."

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

print(arr)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [47]:
# ques34-"Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing."

def check_condition(arr, condition1, condition2):
    result = arr[(condition1) & (condition2)]
    return result   

arr=np.array([1,2,3,4,5,6,7,8,9,10])

condition1 = arr % 2 == 0
condition2 = arr > 5

result = check_condition(arr, condition1, condition2)

print(result)

[ 6  8 10]


In [50]:
#ques35-"Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays."

def extract_elements(array, row_indices, col_indices):
    return array[row_indices, col_indices]


array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])

result = extract_elements(array, row_indices, col_indices)
print(result)

[2 9]


In [3]:
#ques36-"Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting."

import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

result=arr+5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
# ques37-"Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting."

arr1=np.array([[1,2,3]])

arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr1*arr2.T)


[[ 1 10 27]
 [ 2 12 30]
 [ 3 14 33]
 [ 4 16 36]]


In [13]:
# ques38-"Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting."

arr1=np.array([[1,2,3,4]])

arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(arr1+arr2.T)


[[ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [10]:
# ques39-"Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting."

arr1=np.array([[1],[2],[3]])

aar2=np.array([[1,2,3]])

print(arr1+aar2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [20]:
# ques40-" Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility"

arr1=np.array([[1,2,3],
             [4,5,6]])

arr2=np.array([[2,3],
              [4,5]])

arr2_expanded = np.expand_dims(arr2, axis=-1)

result = arr1 * arr2_expanded

print(result)



[[[ 2  4  6]
  [12 15 18]]

 [[ 4  8 12]
  [20 25 30]]]


In [28]:
# ques41-" Calculate column wise mean for the given array:"

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(np.mean(arr, axis=0))



[2.5 3.5 4.5]


In [30]:
# ques42-"Find maximum value in each row of the given array:"

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.max(arr, axis=1))


[3 6]


In [31]:
# ques43="For the given array, find indices of maximum value in each column"

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(np.argmax(arr, axis=0))

[1 1 1]


In [42]:
# ques44-" For the given array, apply custom function to calculate moving sum along rows."

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr):
    return np.sum(arr, axis=1)

print(moving_sum(arr))

[ 6 15]


In [44]:
# ques45-"In the given array, check if all elements in each column are even."

arr = np.array([[2, 4, 6], [3, 5, 7]])

print(np.all(arr % 2 == 0,axis=0))

[False False False]


In [45]:
# ques46-"Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
# reshaped matrix."

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = original_array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [46]:
# ques47-"Create a function that takes a matrix as input and returns the flattened array."

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [2]:
# ques48-". Write a function that concatenates two given arrays along a specified axis."

import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((array1, array2), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
# ques49-" Create a function that splits an array into multiple sub-arrays along a specified axis."

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(array, axis):
    return np.split(array, axis)

split_array(original_array, 1)




[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [10]:
# ques50-"Write a function that inserts and then deletes elements from a given array at specified indices."

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


new_array = np.insert(original_array, indices_to_insert, values_to_insert)

new_array = np.delete(new_array, indices_to_delete)

print(new_array)

[ 1 10  4 11  5]


In [17]:
# ques51-"Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`."

arr1=np.random.randint(1,100,10)
arr2=np.arange(1,11)

result=arr1+arr2

print("Array1:",arr1)
print("Array2:",arr2)
print("Result:",result)

Array1: [33 27 50 10 20 32 43 90 11 24]
Array2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [34 29 53 14 25 38 50 98 20 34]


In [31]:
# ques52-" Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise."

arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)

result=arr1-arr2

print("Array1:",arr1)
print("Array2:",arr2)

print("Result:",result)

Array1: [10  9  8  7  6  5  4  3  2  1]
Array2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [35]:
# ques53-" Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`."

arr1=np.random.randint(1,100,5)
arr2=np.arange(1,6)

result=arr1*arr2

print("Array1:",arr1)
print("Array2:",arr2)
print("Result:",result)

Array1: [59 57 92 49 73]
Array2: [1 2 3 4 5]
Result: [ 59 114 276 196 365]


In [38]:
# ques54-"Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`."

arr1=np.arange(2,12,2)
arr2=np.arange(1,6)

print("Array1:",arr1)
print("Array2:",arr2)
print("Division of Array1 by Array2:",arr1/arr2)

Array1: [ 2  4  6  8 10]
Array2: [1 2 3 4 5]
Division of Array1 by Array2: [2. 2. 2. 2. 2.]


In [39]:
# ques55-"Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of
#  `arr1` raised to the power of `arr2` element-wise."

arr1=np.arange(1,6)
arr2=np.arange(5,0,-1)

print(arr1)
print(arr2)

print(np.power(arr1,arr2))



[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


In [48]:
# ques56-"Write a function that counts the occurrences of a specific substring within a NumPy array of strings."

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring='hello'):
    count = 0
    for i in arr:
        if substring in i:
            count += 1
    return count

print(count_substring(arr))


3


In [49]:
# ques57-"Write a function that extracts uppercase characters from a NumPy array of strings"

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    return [char for word in arr for char in word if char.isupper()]

print(extract_uppercase(arr))

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [50]:
# ques58-" Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string."

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
    for i in range(len(arr)):
        if old_substring in arr[i]:
            arr[i] = arr[i].replace(old_substring, new_substring)
    return arr

print(replace_substring(arr, 'a', 'o'))

['opple' 'bonono' 'grope' 'pineopple']


In [54]:
# ques59-"Write a function that concatenates strings in a NumPy array element-wise."

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

print(np.char.add(arr1, arr2))


['HelloOpen' 'WorldAI']


In [55]:
# ques60-" Write a function that finds the length of the longest string in a NumPy array."

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string(arr):
    longest = arr[0]
    for i in arr:
        if len(i) > len(longest):
            longest = i
    return longest

print(longest_string(arr))

pineapple


In [10]:
# ques61-"Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions."

import numpy as np

dataset=np.random.randint(1,1000,100)

print("Random Dataset:",dataset)
print("Mean of data:",np.mean(dataset))
print("Median of data:",np.median(dataset))
print("Variance Of data:",np.var(dataset))
print("Standard Deviation of data:",np.std(dataset))
print("Maxiumum value of data:",np.max(dataset))



Random Dataset: [ 71 577 536 350 158 874  31 536 197 503 945 558 797  13 920 610 687 875
 515 431 576 334 353  98 520 392 307 169 448 653 674 533 609 331  70 288
 560 957 535  92 671 359 154 436 857 775 276 680 364 843 843 311 360 983
 629 145 597 897 658  87 975 999 745 243 476 725 321 573 751 352 405  35
 318 871 835 488 370 391 336 993 774 788 954 436 391 951 897 779 952 469
 730  34 230 387 754  35 222 329 190 228]
Mean of data: 513.4
Median of data: 509.0
Variance Of data: 77696.88
Standard Deviation of data: 278.74160077031917
Maxiumum value of data: 999


In [17]:
#ques62- "Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset."

arr=np.random.randint(1,100,50)

print(f"Dataset{arr}")
print("25th Percentile of dataset:",np.percentile(arr,25))
print("75th Percentile of dataset:",np.percentile(arr,75))

Dataset[43 61 66 41 59 69 66 68 42 44 89 84 23 38 48 22  7 10 63 11 79 10 57 10
 61 60 12 49 51 47 12 90 84 60 65 41 18 92  8 86 67 27 21 59 58 91 93 81
 43 90]
25th Percentile of dataset: 29.75
75th Percentile of dataset: 67.75


In [20]:
# ques63-"Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function"

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

correlation_coefficient = np.corrcoef(x, y)
print(correlation_coefficient)

[[1. 1.]
 [1. 1.]]


In [21]:
# ques64-"Create two matrices and perform matrix multiplication using NumPy's `dot` function"

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dot(a, b)

print(c)

[[19 22]
 [43 50]]


In [27]:
# ques65-"Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles."

arr=np.random.randint(10,1000,50)

print("Dataset:",arr)
print(f"Median of the 10th, 50th, 90th percentiles:{np.percentile(arr,[10,50,90])}")  

Dataset: [832  63 158 899 769 584 876 235 572 133  68 686 446 551 759 930 194 154
 838 164 945  77 828 127 953 534 341 158 823  78 195  67 985 592 691 349
 105  17 965 400 691 216 401 483 871 113 839 829 331 103]
Median of the 10th, 50th, 90th percentiles:[ 77.9 464.5 902.1]


In [28]:
# ques66-"Create a NumPy array of integers and find the index of a specific element."

arr=np.array([1,2,3,4,5,6,7,8,9,10])

print(arr)
print(np.where(arr==5))

[ 1  2  3  4  5  6  7  8  9 10]
(array([4]),)


In [30]:
# ques67-"Generate a random NumPy array and sort it in ascending order."

arr=np.random.randint(1,100,10)

print(arr)

print(np.sort(arr))
# print(np.sort(arr)[::-1])

[25 11 16 75 90 28 38 37 88 34]
[11 16 25 28 34 37 38 75 88 90]
[90 88 75 38 37 34 28 25 16 11]


In [34]:
# ques68-"Filter elements >20  in the given NumPy array."

arr = np.array([12, 25, 6, 42, 8, 30])

print(arr[arr > 20])

[25 42 30]


In [35]:
# ques69-" Filter elements which are divisible by 3 from a given NumPy array"
arr = np.array([1, 5, 8, 12, 15])

print(arr)
print(arr[arr%3==0])

[ 1  5  8 12 15]
[12 15]


In [40]:
# 70-". Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array."

arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(arr[(arr>=20) & (arr<=40)])

[10 20 30 40 50]
[20 30 40]


In [41]:
# ques71-"For the given NumPy array, check its byte order using the `dtype` attribute byteorder."

arr = np.array([1, 2, 3])

print(arr.dtype.byteorder)


=


In [44]:
# ques72-"For the given NumPy array, perform byte swapping in place using `byteswap()`."

arr = np.array([1, 2, 3], dtype=np.int32)

print(arr.dtype)

arr.byteswap(True)

print(arr)


int32
[16777216 33554432 50331648]


In [49]:
# ques73-"For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`."

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

new_arr = arr.view(arr.dtype.newbyteorder())
print("Swapped byte order array:", new_arr)

print("Original array after swapping byte order:", arr)


Original array: [1 2 3 4 5]
Swapped byte order array: [ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744 360287970189639680]
Original array after swapping byte order: [1 2 3 4 5]


In [51]:
# ques74-"For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`."

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    swapped_arr = arr.byteswap().view(arr.dtype.newbyteorder())

print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)




Original array: [1 2 3]
Swapped byte order array: [1 2 3]


In [53]:
# ques75-". For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`."

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '=':
    system_endianness = "native"
elif byte_order == '<':
    system_endianness = "little-endian"
elif byte_order == '>':
    system_endianness = "big-endian"

print("Array Byte Order:", byte_order)
print("System Endianness:", system_endianness)


Array Byte Order: =
System Endianness: native


In [54]:
# ques76-"Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`."

import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()

copy_arr[0] = 100

print(arr1)
print(copy_arr)




[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


In [55]:
# ques77-"Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`."

import numpy as np

matrix = np.random.randint(0, 10, (3, 3))
print("Original matrix:")
print(matrix)

view_slice = matrix[:2, :2]
print("Slice from the matrix:")
print(view_slice)

view_slice[0, 0] = 100
print("Modified slice:")
print(view_slice)

print("Original matrix after modifying the slice:")
print(matrix)

Original matrix:
[[1 8 2]
 [6 4 0]
 [6 3 6]]
Slice from the matrix:
[[1 8]
 [6 4]]
Modified slice:
[[100   8]
 [  6   4]]
Original matrix after modifying the slice:
[[100   8   2]
 [  6   4   0]
 [  6   3   6]]


In [56]:
# ques78-" Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`."

import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
print("array_a:", array_a)

view_b = array_a[:, 1:]
print("view_b:", view_b)


view_b += 5
print("view_b after broadcasting:", view_b)

print("array_a after broadcasting:", array_a)


array_a: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
view_b: [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
view_b after broadcasting: [[ 7  8]
 [10 11]
 [13 14]
 [16 17]]
array_a after broadcasting: [[ 1  7  8]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


In [57]:
# ques79-" Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`."

array_a = np.arange(1, 13).reshape((4, 3))
print("Original array_a:")
print(array_a)

view_b = array_a[:, 1]  
print("\nExtracted view_b:")
print(view_b)

view_b += 5
print("\nview_b after adding 5:")
print(view_b)

print("\narray_a after modifying view_b:")
print(array_a)


Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted view_b:
[ 2  5  8 11]

view_b after adding 5:
[ 7 10 13 16]

array_a after modifying view_b:
[[ 1  7  3]
 [ 4 10  6]
 [ 7 13  9]
 [10 16 12]]


In [58]:
# ques80-"Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`."

data = np.random.randint(10, size=(3, 4))
print("Original array:")
print(data)

data_copy = data[data > 5]
print("\nCopy of elements greater than 5:")
print(data_copy)

data_copy[0] = 100
print("\nModified data_copy:")
print(data_copy)

print("\nOriginal data:")
print(data) 



Original array:
[[9 8 1 1]
 [2 2 8 2]
 [0 2 5 8]]

Copy of elements greater than 5:
[9 8 8 8]

Modified data_copy:
[100   8   8   8]

Original data:
[[9 8 1 1]
 [2 2 8 2]
 [0 2 5 8]]


In [64]:
# ques81-"Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them."

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("A:", A)
print("\nB:", B)

C = A + B
print("\nAddition:", C)

D = A - B
print("\nSubtraction:", D)

A: [[1 2 3]
 [4 5 6]
 [7 8 9]]

B: [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction: [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [75]:
# ques82-" Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication."

import numpy as np

C = np.random.randint(10, size=(3, 2))
D = np.random.randint(10, size=(2, 4))

print("Matrix C:\n",C)

print("Matrix D:\n",D)


Matrix C:
 [[9 9]
 [3 4]
 [5 2]]
Matrix D:
 [[5 9 0 7]
 [5 7 4 0]]


In [76]:
# ques83-"Create a matrix `E` and find its transpose."

import numpy as np

E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("E:", E)

print("Transpose of E:", E.T)



E: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of E: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [77]:
# ques84-"Generate a square matrix `F` and compute its determinant."

import numpy as np  

F = np.random.randint(1,10, size=(3,3))
print(F)
print(np.linalg.det(F)) 



[[7 8 7]
 [6 7 6]
 [3 8 9]]
6.000000000000027


In [79]:
# ques85-"Create a square matrix `G` and find its inverse."

import numpy as np

G = np.random.randint(1, 10, (3, 3))
print("G = \n", G)

G_inv = np.linalg.inv(G)
print("G_inv = \n", G_inv)

print("G * G_inv = \n", np.dot(G, G_inv))






G = 
 [[4 5 6]
 [6 5 4]
 [6 9 9]]
G_inv = 
 [[ 3.00000000e-01  3.00000000e-01 -3.33333333e-01]
 [-1.00000000e+00 -8.32667268e-17  6.66666667e-01]
 [ 8.00000000e-01 -2.00000000e-01 -3.33333333e-01]]
G * G_inv = 
 [[ 1.00000000e+00  1.66533454e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16  2.49800181e-16  1.00000000e+00]]
